--- 
- 
  hosts: mongodb
  remote_user: azureuser
  tasks: 
    - 
      filesystem: 
        dev: "{{ item }}"
        fstype: xfs
      name: "mkfs xfs on \"{{ mongodb_vm_volumes }}\""
      with_items: 
        - "{{ mongodb_vm_volumes }}"
    - 
      file: 
        path: "{{ item }}"
        state: directory
      name: "mkdir \"{{ mongodb_vm_mountpoints }}\""
      with_items: 
        - "{{ mongodb_vm_mountpoints }}"
    - 
      mount: 
        fstype: xfs
        opts: "default,nofail"
        path: "{{ item.0 }}"
        src: "{{ item.1 }}"
        state: mounted
      name: "mount \"{{ mongodb_vm_volumes }}\" on \"{{ mongodb_vm_mountpoints }}\""
      with_together: 
        - "{{ mongodb_vm_mountpoints }}"
        - "{{ mongodb_vm_volumes }}"
