--- 
- 
  hosts: zabbixagent
  tasks: 
    - 
      name: "start zabbixagent"
      systemd: 
        daemon_reload: true
        enabled: true
        name: zabbix-agent
        state: started
  user: azureuser
