--- 
- 
  hosts: "{{ hosts }}"
  tasks: 
    - 
      group: "name={{ item.gname }} gid={{ item.gid }} state=present"
      name: "create user groups"
      with_items: 
        - 
          gid: 550
          gname: www
        - 
          gid: 551
          gname: mongod
        - 
          gid: 600
          gname: sudo
        - 
          gid: 560
          gname: liangjixin
        - 
          gid: 561
          gname: fengzhibin
        - 
          gid: 562
          gname: chenxuanxin
        - 
          gid: 563
          gname: linxuzhou
    - 
      name: "create users and add into groups"
      user: "name={{ item.name }} group={{ item.group }} groups={{ item.groups }} uid={{ item.uid }} shell=/bin/bash state=present"
      with_items: 
        - 
          append: yes
          group: www
          groups: www
          name: www
          uid: 550
        - 
          append: yes
          group: mongod
          groups: mongod
          name: mongod
          uid: 551
        - 
          group: liangjixin
          groups: sudo
          name: liangjixin
          uid: 560
        - 
          group: fengzhibin
          groups: sudo
          name: fengzhibin
          uid: 561
        - 
          group: chenxuanxin
          groups: sudo
          name: chenxuanxin
          uid: 562
        - 
          group: linxuzhou
          groups: sudo
          name: linxuzhou
          uid: 564
  user: azureuser
