--- 
- 
  file: "path={{ mongodb_data_dir }}/shard{{ id }} owner=mongodb group=mongodb state=directory"
  name: "create mongodb shard directory"
  
- 
  file: "path={{ mongodb_data_dir }}/shard{{ id }}/{{ item }} owner=mongodb group=mongodb state=directory"
  name: "create mongodb shard subdirectory"
  with_items: 
    - log
    - run
    - data
