--- 
- 
  file: "path={{ mongodb_data_dir }}/configserver owner=mongodb group=mongodb state=directory"
  name: "create mongodb configserver directory"
- 
  file: "path={{ mongodb_data_dir }}/configserver/{{ item }} owner=mongodb group=mongodb state=directory"
  name: "create mongodb configserver subdirectory"
  with_items: 
    - log
    - data
    - run
